FROM docker.io/library/alpine:latest

WORKDIR /usr/local/bin

# Install runtime dependencies
RUN apk add --no-cache \
    ca-certificates \
    sqlite-libs \
    libgcc

# Copy the binary
COPY void-eid-backend .

# Expose the API port
EXPOSE 5038

# Run the binary
RUN chmod +x ./void-eid-backend
CMD ["./void-eid-backend"]
