services:
  backend:
    image: ghcr.io/scetrov/void-eid/void-eid-backend@sha256:86e12178954c0d08f6856f1b370b92ff0227cab17b14668ca1ed10619bb00b71
    ports:
      - "5038:5038"
    env_file: ../../.env
    environment:
      - PORT=5038
    volumes:
      - backend-data:/data
    restart: unless-stopped
    networks:
      - shared_net

  murmur:
    image: ghcr.io/scetrov/void-eid/void-eid-murmur@sha256:82d03b600ce54525640cee1505a15f0bae51e2eb3e1bd3320c9e22623766af64
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    env_file: ../../.env
    volumes:
      - murmur-data:/data
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    networks:
      - shared_net

  frontend:
    image: ghcr.io/scetrov/void-eid/void-eid-frontend@sha256:8a5eb7c29781b7509a097acff9114d945fa7de1e9e1cfdd011263b05396ba136
    ports:
      - "5173:8080"
    env_file: ../../.env
    restart: unless-stopped
    networks:
      - shared_net

networks:
  shared_net:
    driver: bridge

volumes:
  backend-data:
    driver: local
  murmur-data:
    driver: local
