/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RosterIndexRouteImport } from './routes/roster/index'
import { Route as RosterIdRouteImport } from './routes/roster/$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIdRoute = RosterIdRouteImport.update({
  id: '/roster/$id',
  path: '/roster/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRoute
  '/voice': typeof VoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/roster/$id': typeof RosterIdRoute
  '/roster/': typeof RosterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRoute
  '/voice': typeof VoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/roster/$id': typeof RosterIdRoute
  '/roster': typeof RosterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRoute
  '/voice': typeof VoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/roster/$id': typeof RosterIdRoute
  '/roster/': typeof RosterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/super-admin'
    | '/voice'
    | '/auth/callback'
    | '/roster/$id'
    | '/roster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/super-admin'
    | '/voice'
    | '/auth/callback'
    | '/roster/$id'
    | '/roster'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/super-admin'
    | '/voice'
    | '/auth/callback'
    | '/roster/$id'
    | '/roster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SuperAdminRoute: typeof SuperAdminRoute
  VoiceRoute: typeof VoiceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RosterIdRoute: typeof RosterIdRoute
  RosterIndexRoute: typeof RosterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$id': {
      id: '/roster/$id'
      path: '/roster/$id'
      fullPath: '/roster/$id'
      preLoaderRoute: typeof RosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SuperAdminRoute: SuperAdminRoute,
  VoiceRoute: VoiceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RosterIdRoute: RosterIdRoute,
  RosterIndexRoute: RosterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
